-- CreateTable
CREATE TABLE "InitialAssessment" (
    "id" TEXT NOT NULL,
    "caseId" TEXT NOT NULL,
    "claimReference" TEXT,
    "fullName" TEXT,
    "address" TEXT,
    "postCode" TEXT,
    "dateMovedIn" TEXT,
    "dateOfBirth" TEXT,
    "niNumber" TEXT,
    "dlNumber" TEXT,
    "dlIssue" TEXT,
    "dlExpiry" TEXT,
    "claimantContactNumber" TEXT,
    "emailAddress" TEXT,
    "accidentLocation" TEXT,
    "accidentCircumstances" TEXT,
    "dateOfAccident" TEXT,
    "timeOfAccident" TEXT,
    "livedInCurrentAddress3Years" TEXT,
    "address2" TEXT,
    "address2Dates" TEXT,
    "address3" TEXT,
    "address3Dates" TEXT,
    "defendantName" TEXT,
    "defendantReg" TEXT,
    "defendantContactNumber" TEXT,
    "defendantMakeModelColor" TEXT,
    "claimantVehicleRegistration" TEXT,
    "claimantInsurer" TEXT,
    "claimantMakeModel" TEXT,
    "mainPolicyHolder" TEXT,
    "additionalDriver1" TEXT,
    "additionalDriver2" TEXT,
    "additionalDriver3" TEXT,
    "noClaimsBonus" TEXT,
    "insuranceType" TEXT,
    "dateLicenceObtained" TEXT,
    "occupation" TEXT,
    "ukResidentFromBirth" TEXT,
    "ukResidentSince" TEXT,
    "vehicleValidMOTAndTax" TEXT,
    "everDeclaredBankrupt" TEXT,
    "claimantClaimingInjury" TEXT,
    "additionalInformation" TEXT,
    "accessToOtherVehicles" TEXT,
    "ownTheVehicle" TEXT,
    "vehicleOwnerRelationship" TEXT,
    "carOnFinance" TEXT,
    "workInMotorTrade" TEXT,
    "needForPrestigeVehicle" TEXT,
    "privateHireLicenceYears" TEXT,
    "taxiIncomePercent" TEXT,
    "additionalEmployment" TEXT,
    "witnessName" TEXT,
    "witnessContactNumber" TEXT,
    "witnessDetailsObtained" TEXT,
    "witnessRelationToClaimant" TEXT,
    "witnessAdditionalInformation" TEXT,
    "nonStandardDriver" BOOLEAN,
    "agedBetween25And70" BOOLEAN,
    "fullUKOrEUDrivingLicense2Years" BOOLEAN,
    "taxiLicence1Year" BOOLEAN,
    "ukResident3Years" BOOLEAN,
    "noMoreThan9PenaltyPoints" BOOLEAN,
    "notBannedFromDriving5Years" BOOLEAN,
    "noMoreThan1FaultClaim2Years" BOOLEAN,
    "noNonSpentCriminalConvictions" BOOLEAN,
    "noDisabilityOrMedicalCondition" BOOLEAN,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InitialAssessment_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "InitialAssessment_caseId_idx" ON "InitialAssessment"("caseId");

-- AddForeignKey
ALTER TABLE "InitialAssessment" ADD CONSTRAINT "InitialAssessment_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE CASCADE ON UPDATE CASCADE;
